---
additionalArgs:
- -x
- checkSigningRequirements
repositories:
- spring-plugins-milestone
preBuildScript: |
  # echo foo
  sed -i '/options.addStringOption/d' build.gradle
  sed -i '/.*group: "org.springframework.build.gradle".*/d' build.gradle
  sed -i '/.*propdeps.*/d' build.gradle
  [[ -f project.gradle ]] && sed -i -e 's/provided/compileOnly/' project.gradle
  [[ -f build.gradle ]] && sed -i -e 's/provided/compileOnly/' build.gradle
